### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aq1** [aq1/Hospital-Helper-2#1]
- [x] Make CRUD widget code tidier
- [x] Maybe refactor gui part at all.
- [x] Fix codecov.
- [x] Deal with deploying.
- [x] Add templates creation.
- [x] Fix CRUD widget so it can actually edit and delete.
- [x] Make names more common: Doctor -> User, Hospital -> Group/Organization.
- [x] Create Users and Groups widget.
- [x] Allow foreign items in template editing widget.
- [x] Create fixtures (items and templates)
- [x] Fix calculations
- [x] Add text formatting
- [x] Remove "heart" title
- [ ] Create tests.
- [x] Add search to db tab
- [ ] Add items editing.
- [ ] Think about auto-update system.

**Comment by aq1** [comment]
<img width="650" alt="2017-03-26_19h56_59" src="https://cloud.githubusercontent.com/assets/3045638/24333332/90fa0f48-125e-11e7-872d-246fba0a53ae.png">
